[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
license = "Apache-2.0"
version = "1.0.0"
authors = ["Cedric Hammes <cach30verfl0w@gmail.com>"]
edition = "2021"
readme = "README.md"
