[package]
name = "octavius-common"
categories = ["no-std"]
license.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true

[dependencies]
thiserror.workspace = true